# Generated by Django 4.0.5 on 2022-06-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_game_player_1_alter_game_player_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
