# Generated by Django 4.0.5 on 2022-06-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_game_player_1_alter_game_player_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='map',
            field=models.CharField(default='.........', max_length=9),
        ),
    ]
