# Generated by Django 4.0.5 on 2022-06-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_game_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='map',
            new_name='chart',
        ),
    ]
